spring.datasource.url=jdbc:mysql://localhost:3306/rest_api_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Semantic PostgreSQL Database

spring.semantic.datasource.url=jdbc:postgresql://localhost:5432/semantic_cloud_db
spring.semantic.datasource.username=postgres
spring.semantic.datasource.password=root
spring.semantic.datasource.driver-class-name=org.postgresql.Driver

